### ISSUE TITLE
Error - node_modules/get-port/index.d.ts:5:28 - error TS2304: Cannot find name 'Omit'

### ISSUE THREAD

**Issue by ninjacoder30** [garrylachman/ElectroCRUD#65] opened 2020-01-02 11:19 UTC
Getting Below Error on npm run electron:mac-win-linux

```
> ElectroCRUD@2.5.2 electron:mac-win-linux /var/www/vhosts/ElectroCRUD
> npm run build:prod && electron-builder build --mac --win --linux


> ElectroCRUD@2.5.2 build:prod /var/www/vhosts/ElectroCRUD
> npm run build -- -c production


> ElectroCRUD@2.5.2 build /var/www/vhosts/ElectroCRUD
> npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"


> ElectroCRUD@2.5.2 postinstall:electron /var/www/vhosts/ElectroCRUD
> node postinstall


> ElectroCRUD@2.5.2 electron:serve-tsc /var/www/vhosts/ElectroCRUD
> tsc -p tsconfig-serve.json

node_modules/get-port/index.d.ts:5:28 - error TS2304: Cannot find name 'Omit'.

5  interface Options extends Omit<ListenOptions, 'port'> {
                             ~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ElectroCRUD@2.5.2 electron:serve-tsc: `tsc -p tsconfig-serve.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ElectroCRUD@2.5.2 electron:serve-tsc script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-02T11_13_02_930Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ElectroCRUD@2.5.2 build: `npm run postinstall:electron && npm run electron:serve-tsc && ng build "-c" "production"`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ElectroCRUD@2.5.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-02T11_13_03_037Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ElectroCRUD@2.5.2 build:prod: `npm run build -- -c production`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ElectroCRUD@2.5.2 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-02T11_13_03_108Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! ElectroCRUD@2.5.2 electron:mac-win-linux: `npm run build:prod && electron-builder build --mac --win --linux`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the ElectroCRUD@2.5.2 electron:mac-win-linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-02T11_13_03_172Z-debug.log
```

**Comment by garrylachman** [comment] 2020-01-31 20:51
Cannot reproduce... what is the get-port version you got?
`cat node_modules/get-port/package.json  | grep version`

**Comment by bunny-poooh** [comment] 2020-02-04 18:26
It's Due to version of typescript below 3.5.1.
Go to package.json -> search "typescript" and change version to 3.5.1
Save package.json and run npm install

Worked for me.

**Comment by garrylachman** [comment] 2023-01-26 21:55
This bug is closed as part of preparing of moving to a new v3.
Its 100% new code in React.

Develop branch:
https://github.com/garrylachman/ElectroCRUD/tree/develop

First preview video:
https://youtube.com/watch?v=gJzlxg2jK9g&feature=share

**Closed by garrylachman** 2023-01-26 21:55 UTC
